title: "Learning Reinforcement Learning"
description: "An academic blog documenting my RL research journey"
url: "https://mintaeshkim.github.io"
baseurl: "/learning-rl"

theme: jekyll-theme-slate

markdown: kramdown
highlighter: rouge

# MathJax
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    disable : true

collections:
  posts:
    output: true
    
defaults:
  - scope:
      path: "_pages"
    values:
      layout: default

plugins:
  - jekyll-feed
  - jekyll-seo-tag
